/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-11-30 22:02:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Database.*;

public final class searchresults_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Database");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>SeCure that A|search results</title>\n");
      out.write("\n");
      out.write("<!-- Import external CSS -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"searchresults.css\" />\n");
      out.write("\n");
      out.write("<!-- Import Google Fonts -->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Public+Sans&display=swap\" rel=\"stylesheet\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato|Public+Sans&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Import JavaScript -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<style>\t\n");
      out.write("\t#header{\n");
      out.write("\t\theight: 60px;\n");
      out.write("\t\tbackground-color: #EFEDEF;\n");
      out.write("\t\tcolor:  #7A797A;\n");
      out.write("\t\topacity: 0.95;\n");
      out.write("\t\tz-index: 1;\n");
      out.write("\t\tposition: fixed;\n");
      out.write("\t    top: 0;\n");
      out.write("\t    width: 100%;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#header-left {\n");
      out.write("\t\tfloat:left;\n");
      out.write("\t\twidth:980px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#header-right {\n");
      out.write("\t\tfloat:left;\n");
      out.write("\t\twidth:250px;\n");
      out.write("\t\tmargin-right:0;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("     #header-right #right-button {\n");
      out.write("       text-decoration: none;\n");
      out.write("       color: #EA70A7;\n");
      out.write("     }\n");
      out.write("\n");
      out.write("     #header-right #right-button:hover {\n");
      out.write("       color: #7A797A;\n");
      out.write("     }\n");
      out.write("     \n");
      out.write("     #header-right #left-button {\n");
      out.write("       text-decoration: none;\n");
      out.write("       color: #EA70A7;\n");
      out.write("     }\n");
      out.write("\n");
      out.write("     #header-right #left-button:hover {\n");
      out.write("       color: #7A797A;\n");
      out.write("     }\t\t\n");
      out.write("\t\n");
      out.write("\tbody{\n");
      out.write("\t\tmargin: 0px;\n");
      out.write("\t\tbackground-color: #FFF4F4;\n");
      out.write("\t\tcolor: #FFC7D4;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#choice{\n");
      out.write("\t\tfloat: left;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tline-height: 58px;\n");
      out.write("\t\tmargin-left: 40px;\n");
      out.write("\t\tcolor: #EA70A7;\n");
      out.write("\t\tfont-size: 18px;\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#left-button{\n");
      out.write("\t\tfloat:right;\n");
      out.write("\t\tfont-size: 18px;\n");
      out.write("\t\tline-height: 62px;\n");
      out.write("\t\tcolor: #EA70A7;\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#right-button{\n");
      out.write("\t\tfloat: right;\n");
      out.write("\t\tfont-size: 18px;\n");
      out.write("\t\tline-height: 60px;\n");
      out.write("\t\tcolor: #EA70A7;\n");
      out.write("\t\tmargin-left:40px;\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#search{\n");
      out.write("\t\tfloat: left;\n");
      out.write("\t\tline-height: 60px;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tmargin-left: 30px;\n");
      out.write("\t\tposition:relative;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#input {\n");
      out.write("\t\twidth: 450px;\n");
      out.write("\t\theight: 33px;\n");
      out.write("\t\tborder-radius: 20px;\n");
      out.write("\t\tpadding-right: 30px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.form-control::-webkit-input-placeholder { \n");
      out.write("\t\tfont-family: 'Public Sans', sans-serif;\n");
      out.write("\t\tcolor: #D3D3D3;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#search #icon {\n");
      out.write("\t\tposition: absolute;\n");
      out.write("\t\tpadding-right: 10px;\n");
      out.write("\t\tpadding-top: 22px;\n");
      out.write("\t\tpointer-events: none;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#search:hover > #icon {color:#EA70A7;}\n");
      out.write("\t\n");
      out.write("\t#search .glyphicon {right: 0px;}\n");
      out.write("\t\n");
      out.write("\t.radio{\n");
      out.write("\t\tmargin-right: 15px;\n");
      out.write("\t\tfont-weight: normal;\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t#home-icon-div img {\n");
      out.write("\t\tfloat: left;\n");
      out.write("\t\theight: 35px;\n");
      out.write("\t\tmargin-top: 13px;\n");
      out.write("\t\tmargin-left: 30px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.clear-float{\n");
      out.write("\t\tclear: both;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.gpa{\n");
      out.write("\t\theight: 100%;\n");
      out.write("\t\tdisplay: inline-block;\n");
      out.write("\t\tbackground-color: #183642;\n");
      out.write("\t\tcolor: #FFC7D4;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tborder-radius: 10px;\n");
      out.write("\t\twidth:20%;\n");
      out.write("\t\tpadding-top:20px;\n");
      out.write("\t\tpadding-bottom:20px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#sidebar{\n");
      out.write("\t\tdisplay: inline-block;\n");
      out.write("\t\tborder-radius: 4px;\n");
      out.write("\t\tmargin-top: 57px;\n");
      out.write("\t    margin-right: 4px;\n");
      out.write("\t    height:100%;\n");
      out.write("\t    width:20%;\n");
      out.write("\t    background-color: #183642;\n");
      out.write("\t    overflow-y: scroll;\n");
      out.write("\t    position:fixed;\n");
      out.write("\t/*  float: right;   \n");
      out.write("\t    z-index:1;\n");
      out.write("\t    overflow:hidden; */\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#sidebar-title{\n");
      out.write("\t\ttext-align: center;\t\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#results{\n");
      out.write("\t\tpadding-top: 60px;\n");
      out.write("\t\tmargin: 0 auto;\n");
      out.write("\t\twidth: 80%;\n");
      out.write("\t\tdisplay: inline-block;\n");
      out.write("\t/* \tborder: solid;\n");
      out.write("\t\tborder-color:blue; */\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#result-title {\n");
      out.write("\t\tcolor:grey;\n");
      out.write("\t\tmargin-left: 400px;\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#no-result {\n");
      out.write("\t\tmargin-left: 100px;\n");
      out.write("\t\tcolor:grey;\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t\tfont-size: 20px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#no-recommend {\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t\tfont-size: 16px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#no-result-div {\n");
      out.write("\t\twidth: 80%;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"header\">\n");
      out.write("\t\n");
      out.write("\t<div id=\"header-left\">\n");
      out.write("\t\n");
      out.write("\t\t<form id=\"form\" class=\"form-inline active-pink-4\" name=\"myform\" action=\"SearchServlet\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div id=\"home-icon-div\">\n");
      out.write("\t\t\t\t<a href=\"Homepage.jsp\"><img src=\"home-icon.png\"></a>\n");
      out.write("\t\t\t</div><!-- home icon div -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- Search form -->\n");
      out.write("\t\t\t<div id=\"search\">\n");
      out.write("\t\t\t\t<i id=\"icon\" class=\"glyphicon glyphicon-search\"></i>\n");
      out.write("\t\t\t    <input id=\"input\" name=\"search-bar\" type=\"text\" class=\"form-control form-control-sm mr-3 w-75\" placeholder=\"SEARCH FOR A COURSE\" />\n");
      out.write("\t\t\t</div><!-- search -->\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"choice\">\n");
      out.write("\t\t\t\t<label class=\"radio\"> \n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"radio-button\" value=\"Professor\">\n");
      out.write("\t\t\t\t\tProfessor \n");
      out.write("\t\t\t\t</label><!-- radio -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<label class=\"radio\"> \n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"radio-button\" value=\"Course\"> \n");
      out.write("\t\t\t\t\tCourse\n");
      out.write("\t\t\t\t</label><!-- radio -->\n");
      out.write("\t\t\t</div><!-- choice -->\n");
      out.write("\t\t</form><!-- myform -->\n");
      out.write("\t\n");
      out.write("\t</div><!-- header left -->\n");
      out.write("\t\n");
      out.write("\t<div id=\"header-right\">\n");
      out.write("\n");

	String n = (String)session.getAttribute("username");
	if(n!=null){ //someone logged in

      out.write("\n");
      out.write("\t\t<a href=\"LogoutServlet\"><div id=\"right-button\"> Sign out </div></a>\n");
      out.write("\t\t<a href=\"Upload.jsp\"><div id=\"left-button\"> Upload GPA </div></a>\n");

	}else{

      out.write("\t\t\n");
      out.write("\t\t<a href=\"RegisterPage.jsp\"><div id=\"right-button\"> Register </div></a>\n");
      out.write("\t\t<a href=\"LoginPage.jsp\"><div id=\"left-button\"> Login </div></a> \n");

	}

      out.write("\n");
      out.write("\n");
      out.write("\t</div><!-- header right -->\n");
      out.write("\t<div class='clear-float'></div>\n");
      out.write("\t</div><!-- header -->\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<div id=\"results\">\n");

    String input = request.getParameter("search-bar");

      out.write("\t\n");
      out.write("\t\t<h3 id=\"result-title\">Results for \"");
      out.print( input );
      out.write("\"</h3>\n");
      out.write("\t\t<hr class=\"line\" style=\"width:100%; position:relative;left:0%;margin-top:0;\"></hr>\n");

		Database db = new Database();	
		String searchby = (String)request.getAttribute("resultsby");
		Vector<String> res = new Vector<String>();
		if(searchby==null){
			System.out.println("searchby is null");//for debug
		}
		else{System.out.println("searchby "+searchby);//for debug
		if(searchby.contentEquals("Course")){
			res = db.searchCourseByCourse(input);
		}
		else{
			res = db.searchCourseByProf(input);
		}}
		if(res.size()==0){

      out.write("\n");
      out.write("\t\t<div id='no-result-div'>\n");
      out.write("\t\t\t<p id='no-result'>No results...try again!</p>\n");
      out.write("\t\t</div><!-- no result div -->\n");

		}
		else{
		for(int i=0; i<res.size(); i++){
			String coursename = res.elementAt(i);
			String coursetitle = db.getCourseTitle(coursename);
			String coursedescription=db.getDescription(coursename);
			double gpa = db.getGPA(coursename);
			int temp = (int)(gpa*100);
			gpa = temp/100.0;

      out.write("\n");
      out.write("\t\t<div class=\"single-result\">\n");
      out.write("\t\t\t<div class=\"course-card\">\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"course-id\">\n");

	if(n!=null){ //someone logged in

      out.write("\n");
      out.write("\t\t<a href=\"Detail.jsp?courseName=");
      out.print(coursename);
      out.write("&courseDescription=");
      out.print(coursedescription);
      out.write("\">\n");
      out.write("\t\t\t\t\t");
      out.print(coursename );
      out.write("</a>\n");

	}else{ //guest, no access to details page

      out.write("\t\t\n");
      out.write("\t\t<!-- Trigger/Open The Modal -->\n");
      out.write("\t\t<a name=\"myBtn\">");
      out.print(coursename );
      out.write("</a>\n");

	}

      out.write("\n");
      out.write("\t\t\t\t</div><!-- course id -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<div class=\"course-title\">");
      out.print(coursetitle);
      out.write("</div>\n");
      out.write("\t\t\t\t<div class=\"course-discription\">\n");
      out.write("\t\t\t\t\t<p>");
      out.print(coursedescription);
      out.write("</p>\n");
      out.write("\t\t\t\t</div><!-- course discription -->\n");
      out.write("\t\t\t</div><!-- course card -->\n");
      out.write("\t\t\t<div class=\"gpa\">\n");
      out.write("\t\t\t\t<div class=\"gpa-title\">\n");
      out.write("\t\t\t\t\t<!-- <strong></strong> <br /> -->\n");
      out.write("\t\t\t\t\t<h3 style=\"margin: 0; padding: 0;\">Overall GPA</h3>\n");
      out.write("\t\t\t\t</div><!-- gpa title -->\n");
      out.write("\t\t\t\t<div class=\"gpa-number\">\n");
      out.write("\t\t\t\t");
if(gpa>=0){
      out.write("\n");
      out.write("\t\t\t\t\t<strong>");
      out.print( gpa);
      out.write("</strong>\n");
      out.write("\t\t\t\t");
}else{
      out.write("\n");
      out.write("\t\t\t\t\t<strong>N/A</strong>\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t</div><!-- gpa number -->\n");
      out.write("\t\t\t</div><!-- gpa -->\n");
      out.write("\t\t</div><!-- single result -->\n");
      out.write("\t\t<br>\n");

		}}

      out.write("\n");
      out.write("\t</div><!-- result -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div id=\"sidebar\">\n");
      out.write("\t\t<h2 id=\"sidebar-title\">Recommended</h2>\n");
      out.write("\t\t\n");
	
		Vector<String> recomm = new Vector<String>();
		if(searchby==null){
			System.out.println("searchby is null");//for debug
		}
		else{System.out.println("searchby "+searchby);//for debug
		if(searchby.contentEquals("Course")){
			recomm = db.getRecommendByCourse(input);
		}
		else{
			recomm = db.getRecommendByProf(input);
		}}		
		if(recomm.size()==0){

      out.write("\n");
      out.write("\t\t<p id='no-recommend'>Nothing to recommend:)</p>\n");

		}
		else{
		for(int i=0; i<recomm.size(); i++){
			String coursename = recomm.elementAt(i);
			String coursetitle = db.getCourseTitle(coursename);
			String coursedescription=db.getDescription(coursename);

      out.write("\n");
      out.write("\t\t<div class=\"recommend\">\n");
      out.write("\t\t<div class=\"recommend-title\">\n");
      out.write("\t\t");

	if(n!=null){ //someone logged in

      out.write("\n");
      out.write("\t\t<a href=\"Detail.jsp?courseName=");
      out.print(coursename);
      out.write("&courseDescription=");
      out.print(coursedescription);
      out.write("\">\n");
      out.write("\t\t\t\t\t");
      out.print(coursename );
      out.write("</a>\n");

	}else{ //guest, no access to details page

      out.write("\t\t\n");
      out.write("\t\t<!-- Trigger/Open The Modal -->\n");
      out.write("\t\t<a name=\"myBtn\">");
      out.print(coursename );
      out.write("</a>\n");

	}

      out.write("\n");
      out.write("\t\t</div><!-- recommend-title -->\n");
      out.write("\t\t<p>");
      out.print(coursetitle);
      out.write("</p>\n");
      out.write("\t\t</div><!-- recommend -->\n");

		}}

      out.write("\n");
      out.write("\n");
      out.write("\t</div><!-- side bar -->\n");
      out.write("\n");
      out.write("<!-- The Modal -->\n");
      out.write("<div id=\"myModal\" class=\"modal\">\n");
      out.write("  <!-- Modal content -->\n");
      out.write("  <div class=\"modal-content\">\n");
      out.write("    <span class=\"close\">&times;</span>\n");
      out.write("    <p><strong>Please log in to view course details</strong></p>\n");
      out.write("  </div>\n");
      out.write("</div>\t\n");
      out.write("<script>\n");
      out.write("// Get the modal\n");
      out.write("var modal = document.getElementById(\"myModal\");\n");
      out.write("\n");
      out.write("// Get the button that opens the modal\n");
      out.write("//var btn = document.getElementById(\"myBtn\");\n");
      out.write("var btns = document.getElementsByName(\"myBtn\");\n");
      out.write("\n");
      out.write("// Get the <span> element that closes the modal\n");
      out.write("var span = document.getElementsByClassName(\"close\")[0];\n");
      out.write("\n");
      out.write("// When the user clicks the button, open the modal \n");
      out.write("for(var i=0; i<btns.length; i++){\n");
      out.write("\tbtns[i].onclick = function() {\n");
      out.write("\t  modal.style.display = \"block\";\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("// When the user clicks on <span> (x), close the modal\n");
      out.write("span.onclick = function() {\n");
      out.write("  modal.style.display = \"none\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("// When the user clicks anywhere outside of the modal, close it\n");
      out.write("window.onclick = function(event) {\n");
      out.write("  if (event.target == modal) {\n");
      out.write("    modal.style.display = \"none\";\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
