/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-12-02 03:44:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import Database.Database;

public final class Detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Database.Database");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t<title>Detail Page</title>\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Import external CSS -->\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"DetailPage.css\" />\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Import Google Fonts -->\n");
      out.write("\t\t<link href=\"https://fonts.googleapis.com/css?family=Public+Sans&display=swap\" rel=\"stylesheet\">\n");
      out.write("\t\t<link href=\"https://fonts.googleapis.com/css?family=Lato|Public+Sans&display=swap\" rel=\"stylesheet\">\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- Import JavaScript -->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("\t\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\n");
      out.write("    \t<script type=\"text/javascript\">\n");
      out.write("\t    \t//for debug-Jessie\n");
      out.write("\t    \tconsole.log(\"courseName:\"+\"");
      out.print(request.getParameter("courseName"));
      out.write("\");\n");
      out.write("\t    \tconsole.log(\"courseDescription:\"+\"");
      out.print(request.getParameter("courseDescription"));
      out.write("\");\n");
      out.write("\n");
      out.write("\t\t</script>\n");
      out.write("<style>\n");
      out.write("#header {\n");
      out.write("\theight: 60px;\n");
      out.write("\tbackground-color: #EFEDEF;\n");
      out.write("\tcolor: #7A797A;\n");
      out.write("\topacity: 0.85;\n");
      out.write("\tz-index: 1;\n");
      out.write("\ttop: 0;\n");
      out.write("\twidth: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-left {\n");
      out.write("\tfloat: left;\n");
      out.write("\twidth: 980px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-right {\n");
      out.write("\tfloat: left;\n");
      out.write("\twidth: 280px;\n");
      out.write("\tmargin-right: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-right #right-button {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tcolor: #EA70A7;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-right #right-button:hover {\n");
      out.write("\tcolor: #7A797A;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-right #left-button {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tcolor: #EA70A7;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#header-right #left-button:hover {\n");
      out.write("\tcolor: #7A797A;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("\tmargin: 0px;\n");
      out.write("\tbackground-color: #FFF4F4;\n");
      out.write("\tcolor: #FFC7D4;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#choice {\n");
      out.write("\tfloat: left;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tline-height: 58px;\n");
      out.write("\tmargin-left: 40px;\n");
      out.write("\tcolor: #EA70A7;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#left-button {\n");
      out.write("\tfloat: right;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("\tline-height: 62px;\n");
      out.write("\tcolor: #EA70A7;\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("\tmargin-right: 35px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#right-button {\n");
      out.write("\tfloat: right;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("\tline-height: 60px;\n");
      out.write("\tcolor: #EA70A7;\n");
      out.write("\tmargin-left: 0px;\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#search {\n");
      out.write("\tfloat: left;\n");
      out.write("\tline-height: 60px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tmargin-left: 30px;\n");
      out.write("\tposition: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#input {\n");
      out.write("\twidth: 450px;\n");
      out.write("\theight: 33px;\n");
      out.write("\tborder-radius: 20px;\n");
      out.write("\tpadding-right: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-control::-webkit-input-placeholder {\n");
      out.write("\tfont-family: 'Public Sans', sans-serif;\n");
      out.write("\tcolor: #D3D3D3;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#search #icon {\n");
      out.write("\tposition: absolute;\n");
      out.write("\tpadding-right: 10px;\n");
      out.write("\tpadding-top: 22px;\n");
      out.write("\tpointer-events: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#search:hover>#icon {\n");
      out.write("\tcolor: #EA70A7;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#search .glyphicon {\n");
      out.write("\tright: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".radio {\n");
      out.write("\tmargin-right: 15px;\n");
      out.write("\tfont-weight: normal;\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#home-icon-div img {\n");
      out.write("\tfloat: left;\n");
      out.write("\theight: 35px;\n");
      out.write("\tmargin-top: 13px;\n");
      out.write("\tmargin-left: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#main {\n");
      out.write("\tmargin-left: auto;\n");
      out.write("\tmargin-right: auto;\n");
      out.write("\twidth: 800px;\n");
      out.write("\tcolor: grey;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#course-info {\n");
      out.write("\tpadding-top: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".clear-float {\n");
      out.write("\tclear: both;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#course-name {\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("\tcolor: #336699;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#course-description {\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".right-professor {\n");
      out.write("\tmargin-left: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#term-div, #professor-div {\n");
      out.write("\tborder: 1px solid white;\n");
      out.write("\tborder-radius: 20px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tbackground: white;\n");
      out.write("\tmargin-bottom: 10px;\n");
      out.write("\theight: 37px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#noselect {\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("\tfont-size: 20px;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#average {\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("\tfont-size: 20px;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#specificGPA {\n");
      out.write("\tborder-radius: 40px;\n");
      out.write("\theight: 70px;\n");
      out.write("\twidth: 160px;\n");
      out.write("\tbackground: #336699;\n");
      out.write("\tcolor: #FFC7D4;\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("\tfont-size: 40px;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("\tmargin-left: 320px;\n");
      out.write("\tpadding-top: 5px;\n");
      out.write("\tmargin-top: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#challenging {\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("\tfont-size: 20px;\n");
      out.write("\tmargin-top: 20px;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#recommendRate {\n");
      out.write("\tfont-family: 'Lato', sans-serif;\n");
      out.write("\tfont-size: 20px;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#columnchart_values {\n");
      out.write("\twidth: 750px;\n");
      out.write("\theight: 500px;\n");
      out.write("\tmargin-right: auto;\n");
      out.write("\tmargin-left: auto;\n");
      out.write("\tmargin-top: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#myModal {\n");
      out.write("\tdisplay: none; /* Hidden by default */\n");
      out.write("\tposition: fixed; /* Stay in place */\n");
      out.write("\tz-index: 1; /* Sit on top */\n");
      out.write("\tpadding-top: 200px; /* Location of the box */\n");
      out.write("\tleft: 0;\n");
      out.write("\ttop: 0;\n");
      out.write("\twidth: 100%; /* Full width */\n");
      out.write("\theight: 100%; /* Full height */\n");
      out.write("\toverflow: auto; /* Enable scroll if needed */\n");
      out.write("\tbackground-color: rgb(0, 0, 0); /* Fallback color */\n");
      out.write("\tbackground-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Modal Content */\n");
      out.write("#modal-content {\n");
      out.write("\tbackground-color: #fefefe;\n");
      out.write("\tmargin: auto;\n");
      out.write("\tpadding: 40px;\n");
      out.write("\tborder: 1px solid #888;\n");
      out.write("\twidth: 40%;\n");
      out.write("\tfont-size: 150%;\n");
      out.write("\tcolor: #FFC7D4;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* The Close Button */\n");
      out.write(".close {\n");
      out.write("\tcolor: #aaaaaa;\n");
      out.write("\tfloat: right;\n");
      out.write("\tfont-size: 28px;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".close:hover, .close:focus {\n");
      out.write("\tcolor: #000;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\t</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"header\">\n");
      out.write("\t\n");
      out.write("\t<div id=\"header-left\">\n");
      out.write("\t\n");
      out.write("\t\t<form id=\"form\" class=\"form-inline active-pink-4\" name=\"myform\" action=\"SearchServlet\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div id=\"home-icon-div\">\n");
      out.write("\t\t\t\t<a href=\"Homepage.jsp\"><img src=\"home-icon.png\"></a>\n");
      out.write("\t\t\t</div><!-- home icon div -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- Search form -->\n");
      out.write("\t\t\t<div id=\"search\">\n");
      out.write("\t\t\t\t<i id=\"icon\" class=\"glyphicon glyphicon-search\"></i>\n");
      out.write("\t\t\t    <input id=\"input\" name=\"search-bar\" type=\"text\" class=\"form-control form-control-sm mr-3 w-75\" placeholder=\"SEARCH FOR A COURSE\" />\n");
      out.write("\t\t\t</div><!-- search -->\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"choice\">\n");
      out.write("\t\t\t\t<label class=\"radio\"> \n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"radio-button\" value=\"Professor\">\n");
      out.write("\t\t\t\t\tProfessor \n");
      out.write("\t\t\t\t</label><!-- radio -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<label class=\"radio\"> \n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"radio-button\" value=\"Course\"> \n");
      out.write("\t\t\t\t\tCourse\n");
      out.write("\t\t\t\t</label><!-- radio -->\n");
      out.write("\t\t\t</div><!-- choice -->\n");
      out.write("\t\t</form><!-- myform -->\n");
      out.write("\t\n");
      out.write("\t</div><!-- header left -->\n");
      out.write("\t\n");
      out.write("\t<div id=\"header-right\">\n");

	String coursename = request.getParameter("courseName");
	String coursedescription = request.getParameter("courseDescription");
	Database db = new Database();
	if(coursedescription==null){
		coursedescription = db.getDescription(coursename);
	}
	String n = (String)session.getAttribute("username");
	if(n!=null){ //someone logged in

      out.write("\n");
      out.write("\t\t<a href=\"LogoutServlet\"><div id=\"right-button\"> Sign out </div></a>\n");
      out.write("\t\t<a href=\"Upload.jsp\"><div id=\"left-button\"> Upload GPA </div></a>\n");

	}else{

      out.write("\t\t\n");
      out.write("\t\t<a href=\"RegisterPage.jsp\"><div id=\"right-button\"> Register </div></a>\n");
      out.write("\t\t<a href=\"Homepage.jsp\"><div id=\"left-button\"> Homepage </div></a>\n");

	}

      out.write("\n");
      out.write("\t</div><!-- header right -->\n");
      out.write("\t<div class='clear-float'></div>\n");
      out.write("\t</div><!-- header -->\n");
      out.write("\t\n");
      out.write("<div id=\"main\">\n");
      out.write("\t\n");
      out.write("\t<div id='course-info'>\t\t\n");
      out.write("\t\t<h1 id=\"course-name\">");
      out.print(coursename);
      out.write("</h1>\n");
      out.write("\t\t<h3 id='course-description'>");
      out.print(coursedescription);
      out.write("</h3>\n");
      out.write("\t</div><!-- course info -->\n");
      out.write("\t<hr class=\"line\" style=\"width:100%; position:relative;left:0%;\"></hr>\n");
      out.write("\t\n");
      out.write("\t<table>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td>\n");
      out.write("\t\t\t\t<div id='term-div'>\n");
      out.write("\t\t\t\t\t<h4 style=\"color:#FFC7D4; font-weight:bold;\">Term</h4>\n");
      out.write("\t\t\t\t</div><!-- term div -->\n");
      out.write(" \t\t\t\t<select id=\"term-dropdown\" name=\"term\" onchange=\"select();drawChart();\">\n");
      out.write("\t\t\t\t\t<option value=\"none\">Select a Term</option>\n");
      out.write("\t\t\t\t\t");
				
						//Database db = new Database();
						ArrayList<String> terms = (ArrayList<String>)(db.getTerms(coursename));
					if(terms==null){
						System.out.println("in details,terms:"+terms);	
					}else{
						for(int i = 0; i < terms.size(); i++){
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(terms.get(i));
      out.write('"');
      out.write('>');
      out.print(terms.get(i));
      out.write("</option>\n");
      out.write("\t\t\t\t\t");
 
						}}
					
      out.write("\n");
      out.write("\t\t  \t\t</select>\n");
      out.write("\t\t  \t\n");
      out.write("\t\t  \t<td>\n");
      out.write("\t\t  \t\t<div class='right-professor'>\n");
      out.write("\t\t  \t\t<div id='professor-div'>\n");
      out.write("\t\t  \t\t\t<h4 style=\"color:#FFC7D4; font-weight: bold;\">Professor</h4>\n");
      out.write("\t\t  \t\t</div><!-- professor div -->\n");
      out.write(" \t\t\t\t<select name=\"professor\" id=\"professor-dropdown\" onchange=\"select()\">\n");
      out.write("\t\t\t\t\t<option value=\"none\">Select a Professor</option>\n");
      out.write("\t\t\t\t\t");

						ArrayList<String> professors = (ArrayList<String>)(db.getProfessors(coursename));
					if(terms==null){
						System.out.println("in details,professors:"+terms);	
					}else{	
					for(int i = 0; i < professors.size(); i++){
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(professors.get(i));
      out.write('"');
      out.write('>');
      out.print(professors.get(i));
      out.write("</option>\n");
      out.write("\t\t\t\t\t");
 
						}}
					
      out.write("\n");
      out.write("\t\t  \t\t</select>\n");
      out.write("\t\t  \t\t</div><!-- right professor -->\n");
      out.write("\t\t  \t\n");
      out.write("\t\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\t\n");
      out.write("\t<h1 id=\"noselect\">Please select terms and/or professors to view details :)</h1>\n");
      out.write("\t<h1 id=\"nodata\" style=\"display:none;\">No data available.</h1>\n");
      out.write("\t<h1 id=\"average\" style=\"display:none;\">The average GPA for <span id=\"term\"></span> by <span id=\"professor\"></span> is</h1>\n");
      out.write("\t<div id=\"specificGPA\" style=\"text-align:center;display:none;\"></div>\n");
      out.write("\t<p id=\"challenging\"></p>\n");
      out.write("\t<p id=\"recommendRate\"></p>\n");
      out.write("\t\n");
      out.write("\t<div id=\"columnchart_values\"></div>\n");
      out.write("\t\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("function select(){\t\t\n");
      out.write("\tdocument.getElementById(\"nodata\").style.display=\"none\";\n");
      out.write("\tdocument.getElementById(\"challenging\").style.display=\"none\";\n");
      out.write("\tdocument.getElementById(\"recommendRate\").style.display=\"none\";\n");
      out.write("\tdocument.getElementById(\"average\").style.display=\"none\";\n");
      out.write("\tdocument.getElementById(\"specificGPA\").style.display=\"none\";\n");
      out.write("\tvar term = document.getElementById(\"term-dropdown\").value;\n");
      out.write("\tvar professor = document.getElementById(\"professor-dropdown\").value;\n");
      out.write("\tconsole.log(\"in jsp, term:\"+term);\n");
      out.write("\tconsole.log(\"in jsp, professor:\"+professor);\n");
      out.write("\tif(professor!=\"none\"){\n");
      out.write("\t\tvar names = professor.split(\" \");\n");
      out.write("\t\tvar fname = names[0];\n");
      out.write("\t\tvar lname = names[1];\n");
      out.write("\t\tfname = fname[0].toUpperCase()+fname.substring(1);\n");
      out.write("\t\tlname = lname[0].toUpperCase()+lname.substring(1); \n");
      out.write("\t} \n");
      out.write("\t\n");
      out.write("\tif(term==\"none\" && professor==\"none\"){\n");
      out.write("\t\tdocument.getElementById(\"noselect\").style.display=\"block\";\n");
      out.write("\t\treturn;\n");
      out.write("\t}\n");
      out.write("\telse{\n");
      out.write("\t\tdocument.getElementById(\"noselect\").style.display=\"none\";\n");
      out.write("\t\tdocument.getElementById(\"average\").style.display=\"block\";\n");
      out.write("\t\tdocument.getElementById(\"specificGPA\").style.display=\"block\";\n");
      out.write("\t\tif(term == \"none\"){\n");
      out.write("\t\t\t\tdocument.getElementById(\"term\").innerHTML = \"all terms\";\n");
      out.write("\t\t\t\tdocument.getElementById(\"professor\").innerHTML = fname+\" \"+lname;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\telse if(professor == \"none\"){\n");
      out.write("\t\t\t\tdocument.getElementById(\"term\").innerHTML = term;\n");
      out.write("\t\t\t\tdocument.getElementById(\"professor\").innerHTML = \"all professors\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\telse{\n");
      out.write("\t\t\t\tdocument.getElementById(\"challenging\").style.display=\"block\";\n");
      out.write("\t\t\t\tdocument.getElementById(\"recommendRate\").style.display=\"block\";\n");
      out.write("\t\t\t\tdocument.getElementById(\"term\").innerHTML = term;\n");
      out.write("\t\t\t\tdocument.getElementById(\"professor\").innerHTML = fname+\" \"+lname;\n");
      out.write("\t\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tvar xhr = new XMLHttpRequest();\n");
      out.write(" \txhr.open('GET',\"DetailServlet?term=\"+term+\"&professor=\"+professor+\"&courseName=\"+\"");
      out.print(coursename);
      out.write("\",false);\n");
      out.write(" \txhr.send();\n");
      out.write("\t\n");
      out.write("\t\tconsole.log(xhr.responseText);\n");
      out.write("\t\tvar str = xhr.responseText;\n");
      out.write("\t\tvar arr = str.split(\" \");\n");
      out.write("\t\tif(arr[0]!=-1){\n");
      out.write("\t\t\tdocument.getElementById(\"specificGPA\").innerHTML=arr[0];\n");
      out.write("\t\t\tif(arr[1].trim()!=-1){\n");
      out.write("\t\t\t\tdocument.getElementById(\"challenging\").style.display=\"block\";\n");
      out.write("\t\t\t\tdocument.getElementById(\"challenging\").innerHTML=arr[1].trim()+'% of the students think '+\"");
      out.print(coursename);
      out.write("\"+' with '+fname+' '+lname+' is challenging.';\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif (arr[2].trim() != -1) {\n");
      out.write("\t\t\t\tdocument.getElementById(\"recommendRate\").style.display = \"block\";\n");
      out.write("\t\t\t\tdocument.getElementById(\"recommendRate\").innerHTML = arr[2].trim()+'% of the students recommend Professor '+fname+\" \"+lname+'.';\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tif (arr[1].trim() == -1 || arr[2].trim() == -1) {\n");
      out.write("\t\t\t\tdocument.getElementById(\"challenging\").style.display = \"none\";\n");
      out.write("\t\t\t\tdocument.getElementById(\"recommendRate\").style.display = \"none\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tdocument.getElementById(\"challenging\").style.display = \"none\";\n");
      out.write("\t\t\tdocument.getElementById(\"recommendRate\").style.display = \"none\";\n");
      out.write("\t\t\tdocument.getElementById(\"specificGPA\").style.display = \"none\";\n");
      out.write("\t\t\tdocument.getElementById(\"average\").style.display = \"none\";\n");
      out.write("\t\t\tdocument.getElementById(\"nodata\").style.display = \"block\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tgoogle.charts.load(\"current\", {packages :['corechart']});\n");
      out.write("\tgoogle.setOnLoadCallback(drawChart);\n");
      out.write("\tvar listProfessor = [];\n");
      out.write("\tvar listGPAstring = [];\n");
      out.write("\tfunction drawChart() {\n");
      out.write("\t\tconsole.log(\"in draw chart\");\n");
      out.write("\t\tvar term = document.getElementById(\"term-dropdown\").value;\n");
      out.write("\t\tif (term != \"none\") {\n");
      out.write("\t\t\tvar chart = new google.visualization.ColumnChart(document\n");
      out.write("\t\t\t\t\t.getElementById('columnchart_values'));\n");
      out.write("\t\t\tvar xhttp = new XMLHttpRequest();\n");
      out.write("\t\t\txhttp.open(\"GET\", \"chartServlet?term=\"+document.getElementById(\"term\").innerHTML+ \"&course=\"+\"");
      out.print(request.getParameter("courseName"));
      out.write("\", false);\n");
      out.write("\t\t\n");
      out.write("\t\txhttp.send();\n");
      out.write("\t\tconsole.log(\"draw chart responseText:\"+xhttp.responseText);\n");
      out.write("\t\tif (xhttp.responseText!=null)\n");
      out.write("\t\t{\n");
      out.write("\t\t\tconsole.log(\"in here\"+xhttp.responseText);\n");
      out.write("\t\t\tvar str = xhttp.responseText;\n");
      out.write("\t\t\tvar profandgpa = str.split(\"|\");\n");
      out.write("\t\t\tvar profs = profandgpa[0];\n");
      out.write("\t\t\tvar gpas = profandgpa[1];\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tlistProfessor = profs.split(\",\");\n");
      out.write("\t\t\tlistGPAstring = gpas.split(\",\")\n");
      out.write("\t\t} \n");
      out.write("\t\t\tvar i;\n");
      out.write("\t\t\tvar listGPA = [];\n");
      out.write("\t\t\tfor(i = 0; i < listProfessor.length; i++)\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tconsole.log(listProfessor[i]);\n");
      out.write("\t\t\t\tlistGPA.push(parseFloat(listGPAstring[i]));\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\tconsole.log(\"listProfessor:\"+listProfessor);\n");
      out.write("\t\t\t\tconsole.log(\"listGPA\"+listGPA);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tvar data = google.visualization.arrayToDataTable([\n");
      out.write("      \t\t\t[\"Professor\", \"GPA\", { role: \"style\" } ],\n");
      out.write("       \t\t \t[\"\", 0.0, \"#FFF4F4\"], \n");
      out.write("    \t\t]);\n");
      out.write("\t\t\t\n");
      out.write("     \t\tvar colorList = [\"#809BCE\", \"#95B8D1\", \"#B8E0D2\", \"#D6EADF\", \"#EAC4D5\", \"#E87461\", \"#E0C879\", \"#D5D887\", \"#A1CF6B\", \"#7AC74F\"];\n");
      out.write("\n");
      out.write("   \t\t\tvar i;\n");
      out.write("  \t\t\tvar j  = listProfessor.length;\n");
      out.write("  \t\t\tfor (i = 0; i < j; i++) {\n");
      out.write("  \t\t\t\tconsole.log(listProfessor[i]);\n");
      out.write("  \t\t\t\tconsole.log(listGPA[i]);\n");
      out.write("  \t\t\t\tdata.addRows([[listProfessor[i], listGPA[i], colorList[i]]]);\n");
      out.write("  \t\t\t}\n");
      out.write("\n");
      out.write("    \t\tvar view = new google.visualization.DataView(data);\n");
      out.write("    \t\tview.setColumns(\n");
      out.write("        \t[0, 1,\n");
      out.write("            \t{ \n");
      out.write("        \t\t\tcalc: \"stringify\",\n");
      out.write("                \tsourceColumn: 1,\n");
      out.write("                \ttype: \"string\",\n");
      out.write("                \trole: \"annotation\" \n");
      out.write("                },\n");
      out.write("            2]); \n");
      out.write("\n");
      out.write("\t        var options = {\n");
      out.write("\t        \ttitle: \"GPA of \" + \"");
      out.print(request.getParameter("courseName"));
      out.write("\" + \" in \" + document.getElementById(\"term\").innerHTML,\n");
      out.write("\t        \twidth: 750,\n");
      out.write("\t        \theight: 500,\n");
      out.write("\t        \tbar: {groupWidth: \"90%\"},\n");
      out.write("\t        \tlegend: { position: \"none\" },\n");
      out.write("\t        \tbackgroundColor: '#FFF4F4',\n");
      out.write("\t        };\n");
      out.write("\t        \n");
      out.write("\t      \tchart.draw(view, options);\n");
      out.write("}\t\t \n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</div><!-- main -->\n");
      out.write("\n");
if(n!=null){ 
      out.write("\n");
      out.write("<script>\n");
      out.write("\t\tvar webSocketUri =  'ws://localhost:8080/SeCurethatA/ws';\n");
      out.write("\t\tvar socket = new WebSocket(webSocketUri);\n");
      out.write("\t\tsocket.onopen = function(event) {\n");
      out.write("\t\t\tconsole.log(\"Connected!\");\n");
      out.write("\t\t};\n");
      out.write("\t\t\t\n");
      out.write("\t\tsocket.onmessage = function(event){\n");
      out.write("\t\t\t\t//alert(event.data);\n");
      out.write("\t\t\tdocument.getElementById(\"modal-text\").innerHTML = event.data;\n");
      out.write("\t\t\tdocument.getElementById(\"myModal\").style.display = \"block\";\n");
      out.write("\t\t\tconsole.log(event.data);\n");
      out.write("\t\t};\n");
      out.write("\t\t\t\n");
      out.write("\t\tsocket.onclose = function(event) {\n");
      out.write("\t\t\tconsole.log(\"Disconnected!\");\n");
      out.write("\t\t};\n");
      out.write("</script>\t\n");
} 
      out.write("\t\n");
      out.write("<!-- The Modal -->\n");
      out.write("<div id=\"myModal\" class=\"modal\">\n");
      out.write("  <!-- Modal content -->\n");
      out.write("  <div id=\"modal-content\">\n");
      out.write("    <span class=\"close\">&times;</span>\n");
      out.write("    <p><strong id=\"modal-text\"></strong></p>\n");
      out.write("  </div>\n");
      out.write("</div>\t\n");
      out.write("<script>\n");
      out.write("// Get the modal\n");
      out.write("var modal = document.getElementById(\"myModal\");\n");
      out.write("\n");
      out.write("// Get the <span> element that closes the modal\n");
      out.write("var span = document.getElementsByClassName(\"close\")[0];\n");
      out.write("\n");
      out.write("// When the user clicks on <span> (x), close the modal\n");
      out.write("span.onclick = function() {\n");
      out.write("  modal.style.display = \"none\";\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
