/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-12-01 01:10:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Database.*;

public final class Upload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Database");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Upload</title>\n");
      out.write("\n");
      out.write("<!-- Import external CSS -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"Uploadpage.css\" />\n");
      out.write("<!-- Import Google Fonts -->\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Public+Sans&display=swap\" rel=\"stylesheet\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato|Public+Sans&display=swap\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Import JavaScript -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\tbody {\n");
      out.write("\t\t/* background: #DEC5D2; */\t    \t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#header {\n");
      out.write("\t\tbackground-image: url(images/background1.jpg);\n");
      out.write("\t\t/* background-color: rgba(140, 140, 140, 0.2); */\n");
      out.write("\t    height: 900px;\n");
      out.write("\t    background-size: cover;\n");
      out.write("\t    background-position: center; \n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#topbar {\n");
      out.write("\t\tbackground-color: #EFEDEF;\n");
      out.write("\t\tcolor:  #7A797A;\n");
      out.write("\t\topacity: 0.85;\n");
      out.write("\t\tz-index: 1;\n");
      out.write("\t    top: 0;\n");
      out.write("\t    width: 100%;\n");
      out.write("\t\tposition: fixed;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#header-left {\n");
      out.write("\t\tfloat:left;\n");
      out.write("\t\twidth:980px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#header-right {\n");
      out.write("\t\tfloat:left;\n");
      out.write("\t\twidth:250px; \n");
      out.write("\t\tmargin-right:0;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("    #header-right #right-button {\n");
      out.write("    \ttext-decoration: none;\n");
      out.write("    \tcolor: #EA70A7;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #header-right #right-button:hover {\n");
      out.write("      \tcolor: #7A797A;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    #header-right #left-button {\n");
      out.write("\t    text-decoration: none;\n");
      out.write("\t    color: #EA70A7;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #header-right #left-button:hover {\n");
      out.write("      \tcolor: #7A797A;\n");
      out.write("    }\t\t\n");
      out.write("\t\n");
      out.write("\thtml, body {\n");
      out.write("\t\theight: 100%;\n");
      out.write("\t    margin: 0;\n");
      out.write("\t    padding: 0;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#choice{\n");
      out.write("\t\tfloat: left;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tline-height: 58px;\n");
      out.write("\t\tmargin-left: 40px;\n");
      out.write("\t\tcolor: #EA70A7;\n");
      out.write("\t\tfont-size: 18px;\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#left-button{\n");
      out.write("\t\tfloat:right;\n");
      out.write("\t\tfont-size: 18px;\n");
      out.write("\t\tline-height: 62px;\n");
      out.write("\t\tcolor: #EA70A7;\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#right-button{\n");
      out.write("\t\tfloat: right;\n");
      out.write("\t\tfont-size: 18px;\n");
      out.write("\t\tline-height: 60px;\n");
      out.write("\t\tcolor: #EA70A7;\n");
      out.write("\t\tmargin-left:40px;\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#search{\n");
      out.write("\t\tfloat: left;\n");
      out.write("\t\tline-height: 60px;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tmargin-left: 15px;\n");
      out.write("\t\tposition:relative;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#input {\n");
      out.write("\t\twidth: 450px;\n");
      out.write("\t\theight: 33px;\n");
      out.write("\t\tborder-radius: 20px;\n");
      out.write("\t\tpadding-right: 30px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.form-control::-webkit-input-placeholder { \n");
      out.write("\t\tfont-family: 'Public Sans', sans-serif;\n");
      out.write("\t\tcolor: #D3D3D3;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#search #icon {\n");
      out.write("\t\tposition: absolute;\n");
      out.write("\t\tpadding-right: 10px;\n");
      out.write("\t\tpadding-top: 22px;\n");
      out.write("\t\tpointer-events: none;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#search:hover > #icon {color:#EA70A7;}\n");
      out.write("\t\n");
      out.write("\t#search .glyphicon {right: 0px;}\n");
      out.write("\t\n");
      out.write("\t.radio{\n");
      out.write("\t\tmargin-right: 15px;\n");
      out.write("\t\tfont-weight: normal;\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t#home-icon-div img {\n");
      out.write("\t\tfloat: left;\n");
      out.write("\t\theight: 35px;\n");
      out.write("\t\tmargin-top: 13px;\n");
      out.write("\t\tmargin-left: 40px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.clear-float{\n");
      out.write("\t\tclear: both;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t#footer {\n");
      out.write("\t    text-align: center;\n");
      out.write("\t    background-color: #EFEDEF;\n");
      out.write("\t    color: #7A797A;\n");
      out.write("\t    height: 35px; \n");
      out.write("\t    position: relative;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #footer p{\n");
      out.write("\t    line-height: 35px;\n");
      out.write("\t    margin: 0px;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    #main {\n");
      out.write("    \tbackground-color: rgba(199, 169, 183, 0.6);\n");
      out.write("    \theight: 74%;\n");
      out.write("\t\twidth: 100%;\n");
      out.write("\t\tmargin-right:0;\n");
      out.write("\t\tmargin-top:2%;\t\t \t\n");
      out.write("\t\tmargin-left:0;\n");
      out.write("\t\tmargin-bottom:0;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    h3 {\n");
      out.write("    \tcolor: white;\n");
      out.write("    \ttext-shadow: 0px 2px 2px rgba(0,0,0,0.4);\n");
      out.write("    \tfont-size: 18px;\n");
      out.write("    \tfont-weight: bold;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    .radio-class{\n");
      out.write("    \tcolor: white;\n");
      out.write("    \ttext-shadow: 0px 2px 2px rgba(0,0,0,0.4);\n");
      out.write("    \tfont-size: 16px;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    #placeholder {\n");
      out.write("    \theight: 75px;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    #error_msg {\n");
      out.write("    \tborder-left: 5px solid #cc0000;\n");
      out.write("    \tcolor: #cc0000;\n");
      out.write("    \tfont-weight:bold;\n");
      out.write("    \tmargin-left: 16px;\n");
      out.write("    \twidth:390px;\n");
      out.write("    \tmargin-top: 25px;\n");
      out.write("    \tbackground-color: white;\n");
      out.write("    \tpadding-top:5px;\n");
      out.write("    \tpadding-bottom: 5px;\n");
      out.write("    \tfont-size: 16px;\n");
      out.write("    \tvisibility: hidden;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    #submit{\n");
      out.write("\t\theight: 44px;\n");
      out.write("\t\twidth: 392px;\n");
      out.write("\t\tfont-size: 18px;\n");
      out.write("\t\tfont-weight:bold;\n");
      out.write("\t\tmargin-top: 40px;\n");
      out.write("\t\tpadding-top: 1px;\n");
      out.write("\t\tcolor: white;\n");
      out.write("\t\tborder-radius: 5px;\n");
      out.write("\t\tbackground-color: #D56AA0;\n");
      out.write("\t\tfont-family: 'Lato', sans-serif;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<script>\n");
      out.write("\tvar webSocketUri =  'ws://localhost:8080/SeCurethatA/ws';\n");
      out.write("\tvar socket;\n");
      out.write("\tfunction connectToServer(){\n");
      out.write("\t\tsocket = new WebSocket(webSocketUri);\n");
      out.write("\t\tsocket.onopen = function(event) {\n");
      out.write("\t\t\tconsole.log(\"Connected!\");\n");
      out.write("\t\t};\n");
      out.write("\t\t\n");
      out.write("\t\tsocket.onmessage = function(event){\n");
      out.write("\t\t\talert(event.data);\n");
      out.write("\t\t\tconsole.log(event.data);\n");
      out.write("\t\t};\n");
      out.write("\t\t\n");
      out.write("\t\tsocket.onclose = function(event) {\n");
      out.write("\t\t\tconsole.log(\"Disconnected!\");\n");
      out.write("\t\t};\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction sendMessage() {\n");
      out.write("\t\tsocket.send(\"New Upload!\");\n");
      out.write("\t\treturn false;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction upload(){\n");
      out.write("\t\tvar xhttp = new XMLHttpRequest();\n");
      out.write("\t\tconsole.log(\"course=\" + document.uploadform.course.value + \n");
      out.write("    \t\t\"&term=\" + document.uploadform.term.value +\n");
      out.write("    \t\t\"&professor=\" + document.uploadform.professor.value +\n");
      out.write("    \t\t\"&gpa=\" + document.uploadform.gpa.value +\n");
      out.write("    \t\t\"&recommend=\" + document.uploadform.recommend.value +\n");
      out.write("    \t\t\"&challenging=\" + document.uploadform.challenging.value);\n");
      out.write("\t\t\n");
      out.write("        xhttp.open(\"GET\", \"UploadServlet?course=\" + document.uploadform.course.value + \n");
      out.write("        \t\t\"&term=\" + document.uploadform.term.value +\n");
      out.write("        \t\t\"&professor=\" + document.uploadform.professor.value +\n");
      out.write("        \t\t\"&gpa=\" + document.uploadform.gpa.value +\n");
      out.write("        \t\t\"&recommend=\" + document.uploadform.recommend.value +\n");
      out.write("        \t\t\"&challenging=\" + document.uploadform.challenging.value, false);\n");
      out.write("        xhttp.send();\n");
      out.write("  \t  \tif (xhttp.responseText.trim().length > 0) {\n");
      out.write("          document.getElementById(\"error_msg\").innerHTML = \"ERROR: \"+xhttp.responseText;\n");
      out.write("          error_msg.style.visibility = 'visible';\n");
      out.write("          error_msg.style.color = '#cc0000';\n");
      out.write("  \t\terror_msg.style.borderLeftColor = '#cc0000';\n");
      out.write("        }else{\n");
      out.write("        \tdocument.getElementById(\"error_msg\").innerHTML = \"You have uploaded successfully\";\n");
      out.write("        \terror_msg.style.visibility = 'visible';\n");
      out.write("    \t\terror_msg.style.color = '#36703F';\n");
      out.write("    \t\terror_msg.style.borderLeftColor = '#36703F';\n");
      out.write("    \t\tsendMessage();\n");
      out.write("        }\n");
      out.write("        return false;\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<body onload=\"connectToServer()\">\n");
      out.write("\n");
      out.write("\t<div id=\"header\">\n");
      out.write("\t<div id=\"topbar\">\n");
      out.write("\t<div id=\"header-left\">\n");
      out.write("\t\n");
      out.write("\t\t<form id=\"form\" class=\"form-inline active-pink-4\" name=\"myform\" action=\"SearchServlet\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div id=\"home-icon-div\">\n");
      out.write("\t\t\t\t<a href=\"Homepage.jsp\"><img src=\"home-icon.png\"></a>\n");
      out.write("\t\t\t</div><!-- home icon div -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- Search form -->\n");
      out.write("\t\t\t<div id=\"search\">\n");
      out.write("\t\t\t\t<i id=\"icon\" class=\"glyphicon glyphicon-search\"></i>\n");
      out.write("\t\t\t    <input id=\"input\" name=\"search-bar\" type=\"text\" class=\"form-control form-control-sm mr-3 w-75\" placeholder=\"SEARCH FOR A COURSE\" />\n");
      out.write("\t\t\t</div><!-- search -->\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"choice\">\n");
      out.write("\t\t\t\t<label class=\"radio\"> \n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"radio-button\" value=\"Professor\">\n");
      out.write("\t\t\t\t\tProfessor \n");
      out.write("\t\t\t\t</label><!-- radio -->\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<label class=\"radio\"> \n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"radio-button\" value=\"Course\"> \n");
      out.write("\t\t\t\t\tCourse\n");
      out.write("\t\t\t\t</label><!-- radio -->\n");
      out.write("\t\t\t</div><!-- choice -->\n");
      out.write("\t\t</form><!-- myform -->\n");
      out.write("\t\n");
      out.write("\t</div><!-- header left -->\n");
      out.write("\t\n");
      out.write("\t<div id=\"header-right\">\n");
      out.write("\n");

	String n = (String)session.getAttribute("username");
	if(n!=null){ //someone logged in

      out.write("\n");
      out.write("\t\t<a href=\"LogoutServlet\"><div id=\"right-button\"> Sign out </div></a>\n");

	}else{

      out.write("\t\t\n");
      out.write("\t\t<a href=\"LoginPage.jsp\"><div id=\"right-button\"> Sign In </div></a>\n");

	}

      out.write("\n");
      out.write("\n");
      out.write("\t</div><!-- header right -->\n");
      out.write("\t</div><!-- topbar -->\n");
      out.write("\t<div class='clear-float'></div>\n");
      out.write("\n");
      out.write("\t<div id=\"placeholder\"></div>\n");
      out.write("\t\n");
      out.write("\t<!-- <h3 style=\"text-align:center\">Upload Your GPA</h3>\n");
      out.write("\t<hr class=\"line\" style=\"width:100%; position:relative;left:0%;\"></hr> -->\n");
      out.write("\t\n");
      out.write("\t<div class=\"container\" id='main'>\n");
      out.write("  \t\t<form name=\"uploadform\" method=\"GET\" onsubmit=\"return upload()\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"info col-lg-4\">\n");
      out.write("\t\t\t\t\t<h3>Select a Course</h3>\n");
      out.write("\t\t\t\t\t<select name=\"course\" class=\"input-field\">\n");
      out.write("\t\t\t\t\t");

					Database db = new Database();
					ArrayList<String[]> courses = db.getCourses();
					for(String[] course : courses){
					
      out.write("\n");
      out.write("\t\t\t\t\t    <option value=\"");
      out.print(course[0]);
      out.write('"');
      out.write('>');
      out.print(course[1]);
      out.write("</option>\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\n");
      out.write("\t\t\t  \t\t</select>\n");
      out.write("\t\t\t\t<br />\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t</div><!-- row -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"info col-lg-4\">\n");
      out.write("\t\t\t\t\t<h3>Select a Term</h3>\n");
      out.write("\t\t\t\t\t<select name=\"term\" class=\"input-field\">\n");
      out.write("\t\t\t\t");
for(int i = 2010; i < 2021; i++){
						for(int j =1; j <= 3; j++){
							String termNumber = ""+i+j;
							String term = i+" ";
							if(j==1){ term += "Spring"; }
							else if(j==2){ term += "Summer"; }
							else if(j==3){ term += "Fall"; }
				
      out.write("\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print( termNumber );
      out.write('"');
      out.write('>');
      out.print( term );
      out.write("</option>\n");
      out.write("\t\t\t\t");

						}
					}
				
      out.write("\n");
      out.write("\t\t\t  \t\t</select>\n");
      out.write("\t\t\t\t<br />\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t</div><!-- row -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"info col-lg-4\">\n");
      out.write("\t\t\t\t\t<h3>Select a Professor</h3>\n");
      out.write("\t\t\t\t\t<select name=\"professor\" class=\"input-field\">\n");
      out.write("\t\t\t\t\t");

					ArrayList<String[]> professors = new ArrayList<>();
					professors = db.getProfessors();
					for(String[] professor : professors){
					
      out.write("\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(professor[0]);
      out.write('"');
      out.write('>');
      out.print(professor[1] );
      out.write("</option>\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\n");
      out.write("\t\t\t  \t\t</select>\n");
      out.write("\t\t\t\t<br />\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t</div><!-- row -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"info col-lg-4\">\n");
      out.write("\t\t\t\t\t<h3>What's your GPA?</h3>\n");
      out.write("\t\t\t\t\t<select name=\"gpa\" class=\"input-field\">\n");
      out.write("\t\t\t\t\t<option value = \"4.0\">4.0</option>\n");
      out.write("\t\t  \t\t\t<option value = \"3.7\">3.7</option>\n");
      out.write("\t\t  \t\t\t<option value = \"3.3\">3.3</option>\n");
      out.write("\t\t  \t\t\t<option value = \"3.0\">3.0</option>\n");
      out.write("\t\t  \t\t\t<option value = \"2.7\">2.7</option>\n");
      out.write("\t\t  \t\t\t<option value = \"2.3\">2.3</option>\n");
      out.write("\t\t  \t\t\t<option value = \"2.0\">2.0</option>\n");
      out.write("\t\t  \t\t\t<option value = \"1.7\">1.7</option>\n");
      out.write("\t\t  \t\t</select>\n");
      out.write("\t\t\t\t<br />\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t</div><!-- row -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"info col-lg-4\">\n");
      out.write("\t\t\t\t\t<h3>Do you recommend this course with this professor?</h3>\n");
      out.write("\t\t\t\t\t<input class=\"radio-class\" type=\"radio\" name=\"recommend\" value=\"yes\"><strong class=\"radio-class\"> Yes </strong>\n");
      out.write("  \t\t\t\t\t<input class=\"radio-class\" type=\"radio\" name=\"recommend\" value=\"no\"><strong class=\"radio-class\"> No </strong>\n");
      out.write("\t\t\t\t<br />\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t</div><!-- row -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"info col-lg-4\">\n");
      out.write("\t\t\t\t\t<h3>Is this course challenging for you?</h3>\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"challenging\" value=\"yes\"><strong class=\"radio-class\"> Yes </strong>\n");
      out.write("  \t\t\t\t\t<input type=\"radio\" name=\"challenging\" value=\"no\"><strong class=\"radio-class\"> No </strong>  \t\t\t\t\t\n");
      out.write("\t\t\t\t<br />\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t</div><!-- row -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\">\n");
      out.write("\t\t\t\t\t<input id=\"submit\" type=\"submit\" name=\"submit\"/>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t</div><!-- row -->\n");
      out.write("\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-lg-4\"></div>\n");
      out.write("\t\t\t<div class=\"col-lg-4\" id=\"error_msg\" style=\"background:#EFEDEF\">\n");
      out.write("\t\t\t");
      out.write("\n");
      out.write("\t\t    </div><!-- error-msg -->\n");
      out.write("\t\t    <div class=\"col-lg-4\"></div>\n");
      out.write("\t\t</div><!-- row -->\n");
      out.write("\t</div><!-- container -->\n");
      out.write("\t</div><!-- header -->\n");
      out.write("\t<div id=\"footer\"> <p> Yang Qiao | Kate Hu | Blair Niu | Jessie Zhang | Mage Zhang | Irene Li &copy; 2019 </p> </div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
